## signup and verify email
POST http://localhost:4000/api/v1/users/signup
Content-Type: application/json

{
    "username" : "karim",
    "password" : "karim123",
    "email" : "karimabdelaziz12703@gmail.com",
    "role" : "Admin"
}
### sign in
POST http://localhost:4000/api/v1/users/signin
Content-Type: application/json

{
    "email" : "karimabdelaziz12703@gmail.com",
    "password" : "karim123"
}
###
GET http://localhost:4000/api/v1/users/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzBjMTc4YjlmZmQzMTg1OWIzYmQ3OTMiLCJpYXQiOjE3Mjg4NDY3NzAsImV4cCI6MTcyODkzMzE3MH0.jEIdLkdiNwhtQqyXR0GTBOJAqOCZx4J1O3Oip7alCXc

###
POST http://localhost:4000/api/v1/users/forget-password
Content-Type: application/json

{
    "email" : "karimabdelaziz12703@gmail.com"
}
###
POST http://localhost:4000/api/v1/users/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzBiZWZjYmRmMDZlNzQzOTc1MzdjOWUiLCJpYXQiOjE3Mjg4MzYxMDcsImV4cCI6MTcyODkyMjUwN30.gW61tFkUR1xbS5Nq_zh9JIXG4XvgKq4Iej9KhZbhOm8
Content-Type: application/json

{
    "password" : "kemokonowlaeh"
}
###
POST http://localhost:4000/api/v1/users/change-password
Content-Type: application/json
